# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install_sdk:
    description: "Install Daml SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Install Daml SDK
          command: |
            curl -sSL https://get.daml.com/ | sh /dev/stdin << parameters.version >>
            # idea from https://circleci.com/docs/2.0/env-vars/
            >> $BASH_ENV echo 'export PATH="$HOME/.daml/bin:$PATH"'

  package_quarkus_app:
    description: "Packaging a Quarkus Application"
    parameters:
      application_name:
        type: string
      archive:
        type: string
    steps:
      - run:
          name: Creating Tarball
          working_directory: << parameters.application_name >>/build
          command: |
            zip -r << parameters.archive >> quarkus-app

  sign_artifact:
    description: "Sign Artifact with GnuPG"
    parameters:
      artifact:
        type: string
      target_directory:
        type: string
    steps:
      - run:
          name: "Prepare GPG dir and key file"
          command: |
            export KEY_FILE=$(mktemp)
            export GPG_DIR=$(mktemp -d)
            echo "$gpg_code_signing" | base64 -d > $KEY_FILE
      - run:
          name: "Signing the artifact"
          command: |
            gpg --homedir $GPG_DIR --no-tty --quiet --import $KEY_FILE
            gpg --homedir $GPG_DIR -ab << parameters.artifact >>
      - run:
          name: "Move artifact and signature"
          command: |
            mv << parameters.artifact >> << parameters.target_directory >>
            mv << parameters.artifact >>.asc << parameters.target_directory >>
      - run:
          name: "Cleanup GPG dir and key file"
          when: always
          command: |
            rm -rf $KEY_FILE $GPG_DIR

jobs:
  test_daml_java:
    parameters:
      daml_sdk_version:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          name: Daml Tests
          working_directory: daml-model
          command: |
            daml test --junit .daml/daml-tests.xml
      - store_test_results:
          path: daml-model/.daml/daml-tests.xml
      - run:
          name: Gradle Tests
          working_directory: .
          command: |
            ./gradlew test
      # See: https://circleci.com/docs/collect-test-data/#gradle-junit-test-results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  blackduck_check:
    parameters:
      daml_sdk_version:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          name: Gradle build
          working_directory: .
          command: |
            gradle build -x test
      - run:
          name: Blackduck detect
          command: |
            # TODO remove exclude pip
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
            ci-build digitalasset_rln_us main \
            --logging.level.com.synopsys.integration=DEBUG \
            --detect.excluded.detector.types=pip \
            --detect.notices.report=false \
            --detect.timeout=3600
  make_release:
    parameters:
      daml_sdk_version:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          name: Building Artifacts
          command: |
            ./gradlew clean build
      - package_quarkus_app:
          application_name: "gui-backend"
          archive: "gui-backend.zip"
      - package_quarkus_app:
          application_name: "integration-adapter"
          archive: "integration-adapter.zip"

parameters:
  do_release:
    type: boolean
    default: false

workflows:
  checkout-build-test:
    jobs:
      - test_daml_java:
          daml_sdk_version: "2.5.0"
      - blackduck_check:
          daml_sdk_version: "2.5.0"
          context:
            - blackduck
  release:
#    when: << pipeline.parameters.do_release >>
    jobs:
      - make_release:
          daml_sdk_version: "2.5.0"
          context: npn-publish
