FROM adoptopenjdk/openjdk11:jdk-11.0.11_9
ARG IMAGE_VERSION
RUN mkdir /opt/app
ADD integration-adapter/build/quarkus-app /opt/app/rln-adapter
CMD ["java", "-jar", "/opt/app/rln-adapter/quarkus-run.jar"]
LABEL version=$IMAGE_VERSION
